# Generated by Django 5.0.2 on 2026-04-23 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0002_cita_activo_compra_activo_cotizacion_activo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='total',
            new_name='precio_unitario',
        ),
    ]
