# Generated by Django 5.0.2 on 2026-04-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0003_rename_total_compra_precio_unitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
