# Generated by Django 5.0.2 on 2026-04-23 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0004_compra_cantidad'),
        ('servicios', '0005_alter_producto_tamano'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='permitir_multiple',
            field=models.BooleanField(default=False, help_text='Marcar si el cliente necesita más de un servicio en este bloque', verbose_name='Permitir horario compartido'),
        ),
        migrations.AddField(
            model_name='compra',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='servicios.producto', verbose_name='Producto'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CitaServicioAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.CharField(blank=True, max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_adicionales', to='operaciones.cita')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.servicio')),
            ],
            options={
                'verbose_name': 'Servicio adicional',
                'verbose_name_plural': 'Servicios adicionales',
            },
        ),
    ]
