# Generated by Django 5.0.2 on 2026-04-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0008_cita_duracion_minutos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='duracion_minutos',
        ),
        migrations.AddField(
            model_name='cita',
            name='duracion_horas',
            field=models.FloatField(default=1.0, verbose_name='Duración estimada (horas)'),
        ),
    ]
