# Generated by Django 5.0.2 on 2026-04-27 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0005_cita_permitir_multiple_compra_producto_and_more'),
        ('operaciones', '0006_remove_cita_duracion_minutos_cita_duracion_horas'),
    ]

    operations = [
    ]
