# Generated by Django 5.0.2 on 2026-04-29 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0007_merge_20260427_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='turno',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='cita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_cita', to='operaciones.cita'),
        ),
    ]
