# Generated by Django 5.0.2 on 2026-04-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0004_compra_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='duracion_minutos',
            field=models.PositiveIntegerField(default=60, verbose_name='Duración estimada (min)'),
        ),
    ]
