# Generated by Django 5.0.2 on 2026-04-30 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0008_cita_turno_venta_cita'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='turno',
        ),
    ]
