# Generated by Django 5.0.2 on 2026-05-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0010_ventacabecera_ventadetalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='turno',
            field=models.PositiveIntegerField(blank=True, help_text='Turno asignado al cliente para esta cita', null=True, verbose_name='Número de turno'),
        ),
    ]
