# Generated by Django 5.0.2 on 2026-05-18 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='codigo_confirmacion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
