# Generated by Django 5.0.2 on 2026-04-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('rol', models.CharField(choices=[('estilista', 'Estilista'), ('colorista', 'Colorista'), ('manicurista', 'Manicurista'), ('recepcionista', 'Recepcionista'), ('gerente', 'Gerente')], max_length=50)),
                ('fecha_ingreso', models.DateField()),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['nombre'],
            },
        ),
    ]
