# Generated by Django 5.0.2 on 2026-05-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_empleado_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='años_experiencia',
            field=models.IntegerField(default=0, verbose_name='Años de experiencia'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='comision',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje sobre ventas', max_digits=5, verbose_name='Comisión (%)'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='dias_descanso',
            field=models.CharField(blank=True, help_text='Ej: Domingo, Lunes', max_length=100, null=True, verbose_name='Días de descanso'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='direccion',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='especialidades',
            field=models.TextField(blank=True, help_text='Ej: Corte, Color, Uñas', null=True, verbose_name='Especialidades'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='horario_entrada',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de entrada'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='horario_salida',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de salida'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='sueldo_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Sueldo base'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_ingreso',
            field=models.DateField(verbose_name='Fecha de ingreso'),
        ),
    ]
