# Generated by Django 5.0.2 on 2026-05-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_empleado_años_experiencia_empleado_comision_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='horario_entrada',
            field=models.CharField(blank=True, choices=[('10:00', '10:00 AM'), ('11:00', '11:00 AM'), ('12:00', '12:00 PM'), ('13:00', '01:00 PM'), ('17:00', '05:00 PM'), ('18:00', '06:00 PM'), ('19:00', '07:00 PM'), ('20:00', '08:00 PM')], max_length=10, null=True, verbose_name='Hora de entrada'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='horario_salida',
            field=models.CharField(blank=True, choices=[('10:00', '10:00 AM'), ('11:00', '11:00 AM'), ('12:00', '12:00 PM'), ('13:00', '01:00 PM'), ('17:00', '05:00 PM'), ('18:00', '06:00 PM'), ('19:00', '07:00 PM'), ('20:00', '08:00 PM')], max_length=10, null=True, verbose_name='Hora de salida'),
        ),
    ]
