# Generated by Django 5.0.2 on 2026-05-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.CharField(choices=[('registrado', 'Cliente Registrado'), ('venta_rapida', 'Venta Rápida (Ocasional)')], default='registrado', max_length=20, verbose_name='Tipo de cliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
