# Generated by Django 5.0.2 on 2026-04-23 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_producto_activo_servicio_activo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicio',
            options={'ordering': ['nombre'], 'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
        migrations.AddField(
            model_name='producto',
            name='contenido',
            field=models.CharField(blank=True, help_text='Ej: 250 ml, 1 kg, paquete 12 pzas', max_length=50, verbose_name='Tamaño / Contenido'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='costo',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_actual',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_minimo',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='categoria',
            field=models.CharField(choices=[('corte', 'Corte'), ('color', 'Color'), ('tratamiento', 'Tratamiento'), ('unas', 'Uñas'), ('maquillaje', 'Maquillaje')], max_length=20),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='precio_base',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
