# Generated by Django 5.0.2 on 2026-04-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_alter_servicio_options_producto_contenido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='contenido',
        ),
        migrations.AddField(
            model_name='producto',
            name='tamano',
            field=models.CharField(blank=True, help_text='Medida del producto: Ej: 250 ml, 1 kg', max_length=100, verbose_name='Tamaño'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tamano_personalizado',
            field=models.CharField(blank=True, help_text='Si el tamaño no está en la lista, escríbelo aquí', max_length=100, verbose_name='Tamaño personalizado'),
        ),
    ]
