# Generated by Django 5.0.2 on 2026-04-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_remove_producto_contenido_producto_tamano_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tamano',
            field=models.CharField(blank=True, help_text='Selecciona la medida del producto', max_length=100, verbose_name='Tamaño'),
        ),
    ]
