# Generated by Django 5.0.2 on 2026-04-28 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_alter_producto_tamano'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='presentacion',
            field=models.CharField(blank=True, choices=[('', '— Selecciona presentación —'), ('botella', 'Botella'), ('frasco', 'Frasco'), ('tubo', 'Tubo'), ('sachet', 'Sachet'), ('lata', 'Lata'), ('caja', 'Caja'), ('pieza', 'Pieza'), ('paquete', 'Paquete'), ('otro', 'Otro')], help_text='Tipo de envase o presentación del producto', max_length=50, verbose_name='Presentación'),
        ),
    ]
