# Generated by Django 5.0.2 on 2026-04-29 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_alter_producto_tamano'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='presentacion',
            field=models.CharField(blank=True, choices=[('frasco', 'Frasco'), ('tubo', 'Tubo'), ('pieza', 'Pieza'), ('botella', 'Botella'), ('otro', 'Otro')], default='otro', max_length=20, null=True),
        ),
    ]
