# Generated by Django 5.0.2 on 2026-05-17 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0006_producto_presentacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='servicio',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='servicio',
            name='duracion_minutos',
            field=models.PositiveIntegerField(default=60, verbose_name='Duración (minutos)'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='precio_costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
