# Generated by Django 5.0.2 on 2026-05-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0008_producto_precio_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tamano',
            field=models.CharField(blank=True, help_text='Selecciona la medida del producto', max_length=100, verbose_name='Tamano'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tamano_personalizado',
            field=models.CharField(blank=True, help_text='Si el tamano no esta en la lista, escribelo aqui', max_length=100, verbose_name='Tamano personalizado'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='duracion_minutos',
            field=models.PositiveIntegerField(default=60, verbose_name='Duracion (minutos)'),
        ),
    ]
