# Generated by Django 5.0.2 on 2026-05-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0009_alter_producto_tamano_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tamano',
            field=models.CharField(blank=True, help_text='Selecciona la medida del producto', max_length=100, verbose_name='Tamaño'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tamano_personalizado',
            field=models.CharField(blank=True, help_text='Si el tamaño no está en la lista, escríbelo aquí', max_length=100, verbose_name='Tamaño personalizado'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='duracion_minutos',
            field=models.PositiveIntegerField(default=60, verbose_name='Duración (minutos)'),
        ),
    ]
