# Generated by Django 5.0.2 on 2026-05-18 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0010_alter_producto_tamano_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='imagen',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
